### ISSUE TITLE
Нужно повысить DEFAULT_API_VERSION

### ISSUE THREAD

**Issue by vyacheslavchernov** [bryzgaloff/vk#1]
https://github.com/bryzgaloff/vk/blob/9dee1e0e22b055e1296ea0e76ed5cb26f1541ef3/session.py#L9

Сейчас возникает ошибка:
`vk.exceptions.VkAPIError: 8. Invalid request: versions below 5.81 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates. request_params = {'method': 'users.get', 'oauth': '1', 'v': '5.68', 'user_ids': '1'}`

Обёртка не декларирует сам API, следовательно,  для того, чтобы всё снова заработало значение нужно заменить на 5.81

**Comment by bryzgaloff** [comment]
Спасибо за предложенное исправление 👍 В качестве быстрого решения в следующий раз можно передавать версию API при инициализации сессии: например, `Session(…, v='5.68', …)`.
